name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Firebase CLI
      run: curl -sL https://firebase.tools | bash

    - name: Set GOOGLE_APPLICATION_CREDENTIALS
      run: echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" > $HOME/firebase-service-account-key.json
      env:
        FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}

    - name: Debug Secrets
      run: echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" | jq
      env:
        FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}

    - name: Debug Environment Variable
      run: cat $HOME/firebase-service-account-key.json
      env:
        GOOGLE_APPLICATION_CREDENTIALS: $HOME/firebase-service-account-key.json

    - name: Deploy to Firebase Hosting
      run: firebase deploy --only hosting --project "infomanager-cfd4c" --debug
      env:
        GOOGLE_APPLICATION_CREDENTIALS: $HOME/firebase-service-account-key.json
