name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Firebase CLI
      run: curl -sL https://firebase.tools | bash

    # 디버깅: FIREBASE_TOKEN 확인
    - name: Debug Firebase Token
      run: |
        if [ -z "${{ secrets.FIREBASE_TOKEN }}" ]; then
          echo "FIREBASE_TOKEN is not set or empty!"
          exit 1
        else
          echo "FIREBASE_TOKEN is set."
        fi

    # Firebase Hosting 배포
    - name: Deploy to Firebase Hosting
      run: firebase deploy --only hosting --project "infomanager-cfd4c" --token "${{ secrets.FIREBASE_TOKEN }}"
