name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Firebase CLI
      run: npm install -g firebase-tools

    - name: Set GOOGLE_APPLICATION_CREDENTIALS
      run: echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" > $HOME/firebase-service-account-key.json
      env:
        FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}

    - name: Deploy to Firebase Hosting
      run: firebase deploy --only hosting --project "infomanager-cfd4c"
      env:
        GOOGLE_APPLICATION_CREDENTIALS: $HOME/firebase-service-account-key.json
